### ISSUE TITLE
conda package for MDAnalysisData

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysisData#21]
We need a conda package so that we can easily distribute MDAnalysisData for the workshop.

This can be modelled after https://github.com/MDAnalysis/pmda/issues/74

**Comment by orbeckst** [comment]
@kain88-de if you have any bandwidth – help would be most welcome!

**Comment by kain88-de** [comment]
does a pypi package exist yet?

**Comment by richardjgowers** [comment]
Not yet.  I can put one together this week

**Comment by kain88-de** [comment]
I did find one for a 0.3.0 version. There is a build. You should have
gotten a notice on github

**Comment by orbeckst** [comment]
Yes, I've been pushing to pypi, following https://github.com/MDAnalysis/MDAnalysisData/wiki/DeveloperGuide#release-management

**Comment by orbeckst** [comment]
```
$ conda search MDAnalysisData
Loading channels: done
# Name                  Version           Build  Channel
mdanalysisdata            0.3.0            py_0  conda-forge
```
