### ISSUE TITLE
CG fiber dataset: docs?

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysisData#27]
Is the CG fiber dataset officially released?

If so

- [ ] integrate into docs (usage.rst etc – check how the others were added)
- [ ] CHANGELOG entry

**Comment by richardjgowers** [comment]
fixed

**Comment by orbeckst** [comment]
not quite... see comments

**Comment by orbeckst** [comment]
I'll push the fixes... hold on
