### ISSUE TITLE
generate docs

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysisData#4]
The datasets include docs. They should be built with sphinx and displayed under https://www.mdanalysis.org/MDAnalysisData.

- [x] create sphinx templates
- [x] copy the MDAnalysis styles (local.css, custom.css, and logos)
- [ ] use Travis CI to build docs (they have an option that _should_ allow us to do it automatically with gh-pages)

**Comment by richardjgowers** [comment]
If we redid the repo to use https://github.com/choderalab/cookiecutter-compchem as the base, this might make this easier (and #3)

**Comment by orbeckst** [comment]
Next time...

**Comment by orbeckst** [comment]
For docs: follow the example of [alchemtest](https://github.com/alchemistry/alchemtest), see the [alchemtest docs](https://alchemtest.readthedocs.io/en/latest/)
