### ISSUE TITLE
Make next release 3.6+?

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/MDAnalysisData#51]
Mainly looking at this because of #48, supporting py2.7/py3.5 (if just the act of conda installing an environment) is becoming increasingly tedious.

Given that MDA 2.0 will be py3.6+ and that 2.7 has now long been deprecated, would it be worth making MDAnalysisData's python 3.6->3.9?

**Comment by orbeckst** [comment]
We can... but it also works with the old stuff, according to the tests in PR #52 . (It would have required a bit less duct-taping in the tests if I could have ignored 2.7 but the bigger issue was UNIX vs Windows.)

I want to cut a quick 0.8.1 #53 with legacy included and then we have a firm foundation if we want to drop legacy.

**Comment by orbeckst** [comment]
Went NEP29-ish with PR #61 so this is done.
