### ISSUE TITLE
GH docs workflow fails

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysisData#66]
The docs workflow fails https://github.com/MDAnalysis/MDAnalysisData/actions/runs/6695446777

>    error: invalid command 'build_sphinx'

(see also #65 )

**Comment by IAlibay** [comment]
@orbeckst looks like the action failed but I'm not 100% sure why yet.

**Comment by IAlibay** [comment]
I think I know why, one sec.

**Comment by orbeckst** [comment]
Looking good after #68!
