### ISSUE TITLE
use MDA theme for docs

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysisData#67]
While we're at fixing docs (#65 #66) we should also update to the MDA sphinx theme.

**Comment by orbeckst** [comment]
@lilyminium is there a basic "howto" for updating to the MDA sphinx theme?

**Comment by IAlibay** [comment]
@orbeckst I have a PR open for this - see #64

**Comment by orbeckst** [comment]
Ah, nice, hadn't seen it.
