### ISSUE TITLE
[CI] testing after deployment fails 

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysisData#72]
See https://github.com/MDAnalysis/MDAnalysisData/issues/62#issuecomment-1785944239

🔴 Test after deployment FAILED https://github.com/MDAnalysis/MDAnalysisData/actions/runs/6698031942/job/18199197552
  ```
  ==================================== ERRORS ====================================
  _________________ ERROR at setup of test_fetch_remote_sha_fail _________________
  file /home/runner/work/MDAnalysisData/MDAnalysisData/MDAnalysisData/tests/test_base.py, line   107
    def test_fetch_remote_sha_fail(remote_topology, mocker):
  E       fixture 'mocker' not found
  >       available fixtures: bunch, cache, capfd, capfdbinary, caplog, capsys, capsysbinary,   doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, remote_topology, some_text, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
  >       use 'pytest --fixtures [testpath]' for help on them.
  ```

Need to add packages to the test suite.

**Comment by orbeckst** [comment]
@IAlibay I actually don't know what to do here: the package correctly says it needs pytest-mock for tests: https://github.com/MDAnalysis/MDAnalysisData/blob/f8c9a1af940b4b6740d2aff407bb61e6c2cf0029/setup.py#L154

How does the `MDAnalysis/pypi-deployment@main` action use this information when installing the package for testing?

**Comment by IAlibay** [comment]
@orbeckst - I'm pretty sure there's a way to pass in test dependencies through. I think there's a `test_deps` entry or something that I might have forgotten to advertise on the README. I can look into it but I need a couple hours sleep first 😅 I can play around with it in the morning if needed?

**Comment by orbeckst** [comment]
sure, thanks! I have lots of other things I ought to be doing.
