### ISSUE TITLE
update deprecated use of pkg_resources

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysisData#75]
We use pkg_resources:
```
DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    from pkg_resources import resource_string
```
Use importlib instead, along the line of
```python
import importlib.resources as importlib_resources

__all__ = ["DX", "CCP4", "gOpenMol"]

DX = importlib_resources.files(__name__) / 'test.dx'
```
(from https://github.com/MDAnalysis/GridDataFormats/blob/master/gridData/tests/datafiles/__init__.py where this was recently fixed)

**Comment by IAlibay** [comment]
I'm surprised, I thought that would have failed with Python 3.12 O.O!

**Comment by orbeckst** [comment]
It just versioneer... need to update.
